# Generated by Django 3.2.9 on 2021-12-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
