# Generated by Django 3.2.9 on 2021-12-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_due_data_todo_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
